-- VHDL Entity RTL_project_lib.ripple_carry_adder.symbol
--
-- Created:
--          by - USER.UNKNOWN (DESKTOP-R8G1IGO)
--          at - 10:27:58 11/ 6/2019
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY ripple_carry_adder IS
   PORT( 
      a_in  : IN     std_logic_vector (2 DOWNTO 0);
      b_in  : IN     std_logic_vector (2 DOWNTO 0);
      s_out : OUT    std_logic_vector (3 DOWNTO 0)
   );

-- Declarations

END ripple_carry_adder ;

--
-- VHDL Architecture RTL_project_lib.ripple_carry_adder.struct
--
-- Created:
--          by - USER.UNKNOWN (DESKTOP-R8G1IGO)
--          at - 10:27:58 11/ 6/2019
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ARCHITECTURE struct OF ripple_carry_adder IS

   -- Architecture declarations

   -- Internal signal declarations



BEGIN

   -- Instance port mappings.

END struct;
