# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: P:/Logic_synthesis/21/xdc/synth.xdc

# Block Designs: bd/system_top_level/system_top_level.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_top_level || ORIG_REF_NAME==system_top_level}]

# IP: bd/system_top_level/ip/system_top_level_synthesizer_0_0/system_top_level_synthesizer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_top_level_synthesizer_0_0 || ORIG_REF_NAME==system_top_level_synthesizer_0_0}]

# IP: bd/system_top_level/ip/system_top_level_i2c_config_0_0/system_top_level_i2c_config_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_top_level_i2c_config_0_0 || ORIG_REF_NAME==system_top_level_i2c_config_0_0}]

# IP: bd/system_top_level/ip/system_top_level_clk_wiz_0_0/system_top_level_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_top_level_clk_wiz_0_0 || ORIG_REF_NAME==system_top_level_clk_wiz_0_0}]

# IP: bd/system_top_level/ip/system_top_level_util_vector_logic_0_0/system_top_level_util_vector_logic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_top_level_util_vector_logic_0_0 || ORIG_REF_NAME==system_top_level_util_vector_logic_0_0}]

# IP: bd/system_top_level/ip/system_top_level_util_vector_logic_1_0/system_top_level_util_vector_logic_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_top_level_util_vector_logic_1_0 || ORIG_REF_NAME==system_top_level_util_vector_logic_1_0}]

# XDC: bd/system_top_level/ip/system_top_level_clk_wiz_0_0/system_top_level_clk_wiz_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_top_level_clk_wiz_0_0 || ORIG_REF_NAME==system_top_level_clk_wiz_0_0}] {/inst }]/inst ]]

# XDC: bd/system_top_level/ip/system_top_level_clk_wiz_0_0/system_top_level_clk_wiz_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_top_level_clk_wiz_0_0 || ORIG_REF_NAME==system_top_level_clk_wiz_0_0}] {/inst }]/inst ]]

# XDC: bd/system_top_level/ip/system_top_level_clk_wiz_0_0/system_top_level_clk_wiz_0_0_late.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_top_level_clk_wiz_0_0 || ORIG_REF_NAME==system_top_level_clk_wiz_0_0}] {/inst }]/inst ]]

# XDC: bd/system_top_level/ip/system_top_level_clk_wiz_0_0/system_top_level_clk_wiz_0_0_ooc.xdc

# XDC: bd/system_top_level/system_top_level_ooc.xdc
