# 
# Synthesis run script generated by Vivado
# 

create_project -in_memory -part xc7z020clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir P:/logsyn/syn/synth_top/synth_top.cache/wt [current_project]
set_property parent.project_path P:/logsyn/syn/synth_top/synth_top.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo p:/logsyn/syn/synth_top/synth_top.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  P:/logsyn/verilog/i2c_config.v
  P:/logsyn/syn/synth_top/synth_top.srcs/sources_1/bd/system_top_level/hdl/system_top_level_wrapper.v
}
read_vhdl -library xil_defaultlib {
  P:/logsyn/vhd/adder.vhd
  P:/logsyn/vhd/audio_ctrl.vhd
  P:/logsyn/vhd/multi_port_adder.vhd
  P:/logsyn/vhd/wave_gen.vhd
  P:/logsyn/vhd/synthesizer.vhd
}
add_files P:/logsyn/syn/synth_top/synth_top.srcs/sources_1/bd/system_top_level/system_top_level.bd
set_property used_in_implementation false [get_files -all p:/logsyn/syn/synth_top/synth_top.srcs/sources_1/bd/system_top_level/ip/system_top_level_clk_wiz_0_0/system_top_level_clk_wiz_0_0_board.xdc]
set_property used_in_implementation false [get_files -all p:/logsyn/syn/synth_top/synth_top.srcs/sources_1/bd/system_top_level/ip/system_top_level_clk_wiz_0_0/system_top_level_clk_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all p:/logsyn/syn/synth_top/synth_top.srcs/sources_1/bd/system_top_level/ip/system_top_level_clk_wiz_0_0/system_top_level_clk_wiz_0_0_late.xdc]
set_property used_in_implementation false [get_files -all p:/logsyn/syn/synth_top/synth_top.srcs/sources_1/bd/system_top_level/ip/system_top_level_clk_wiz_0_0/system_top_level_clk_wiz_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all P:/logsyn/syn/synth_top/synth_top.srcs/sources_1/bd/system_top_level/system_top_level_ooc.xdc]
set_property is_locked true [get_files P:/logsyn/syn/synth_top/synth_top.srcs/sources_1/bd/system_top_level/system_top_level.bd]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc P:/logsyn/xdc/synth.xdc
set_property used_in_implementation false [get_files P:/logsyn/xdc/synth.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top system_top_level_wrapper -part xc7z020clg400-1


write_checkpoint -force -noxdef system_top_level_wrapper.dcp

catch { report_utilization -file system_top_level_wrapper_utilization_synth.rpt -pb system_top_level_wrapper_utilization_synth.pb }
